name: GitHub - Activity - Readme

on:
  schedule:
    - cron: '0 0 * * 1,3,5' # Runs every Monday, Wednesday, and Friday at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}